/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.qldl.GUI;

/**
 *
 * @author Thin
 */
public class GiaoDienUngDung extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienUngDung
     */
    public GiaoDienUngDung() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnKhachSan = new javax.swing.JButton();
        btnNhaHang = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        btnPhuongTien = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDesktop = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnTour = new javax.swing.JButton();
        btnKHTour = new javax.swing.JButton();
        btnDiaDiem = new javax.swing.JButton();
        btnHopDong = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        btnThuChi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setForeground(new java.awt.Color(0, 0, 255));
        jPanel4.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon("F:\\QLDL\\image\\doan.PNG")); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel5)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel6);
        jPanel6.setBounds(70, 40, 170, 140);

        jLabel6.setIcon(new javax.swing.ImageIcon("F:\\QLDL\\image\\logoPhuongTien.PNG")); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel7);
        jPanel7.setBounds(360, 40, 170, 140);

        jLabel8.setIcon(new javax.swing.ImageIcon("F:\\QLDL\\image\\logoNhaHang.PNG")); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel8);
        jPanel8.setBounds(70, 240, 170, 130);

        jLabel7.setIcon(new javax.swing.ImageIcon("F:\\QLDL\\image\\logoKhachSan.PNG")); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(jPanel9);
        jPanel9.setBounds(370, 240, 160, 130);

        btnKhachSan.setBackground(new java.awt.Color(102, 0, 0));
        btnKhachSan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnKhachSan.setForeground(new java.awt.Color(255, 255, 0));
        btnKhachSan.setText("KHÁCH SẠN");
        btnKhachSan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachSanActionPerformed(evt);
            }
        });
        jPanel4.add(btnKhachSan);
        btnKhachSan.setBounds(370, 380, 160, 23);

        btnNhaHang.setBackground(new java.awt.Color(102, 0, 0));
        btnNhaHang.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnNhaHang.setForeground(new java.awt.Color(255, 255, 0));
        btnNhaHang.setText("NHÀ HÀNG");
        btnNhaHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhaHangActionPerformed(evt);
            }
        });
        jPanel4.add(btnNhaHang);
        btnNhaHang.setBounds(70, 380, 170, 23);

        jButton13.setBackground(new java.awt.Color(102, 0, 0));
        jButton13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 0));
        jButton13.setText("ĐOÀN");
        jPanel4.add(jButton13);
        jButton13.setBounds(70, 190, 170, 23);

        btnPhuongTien.setBackground(new java.awt.Color(102, 0, 0));
        btnPhuongTien.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPhuongTien.setForeground(new java.awt.Color(255, 255, 0));
        btnPhuongTien.setText("PHƯƠNG TIỆN");
        btnPhuongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhuongTienActionPerformed(evt);
            }
        });
        jPanel4.add(btnPhuongTien);
        btnPhuongTien.setBounds(360, 190, 170, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon("F:\\QLDL\\image\\content.jpg")); // NOI18N
        jPanel4.add(jLabel4);
        jLabel4.setBounds(0, 0, 600, 438);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 0));
        jLabel1.setText("ỨNG DỤNG QUẢN LÝ TOUR DU LỊCH");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Welcom to VNGO Travel");

        btnDesktop.setBackground(new java.awt.Color(255, 0, 0));
        btnDesktop.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDesktop.setForeground(new java.awt.Color(0, 0, 0));
        btnDesktop.setText("->");
        btnDesktop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesktopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDesktop)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnDesktop))
                .addGap(118, 118, 118))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon("F:\\QLDL\\image\\login.PNG")); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 0, 130, 110);

        jPanel5.add(jPanel2);
        jPanel2.setBounds(0, 0, 150, 110);

        jPanel3.setBackground(new java.awt.Color(255, 204, 255));
        jPanel3.setLayout(null);

        btnTour.setBackground(new java.awt.Color(153, 153, 255));
        btnTour.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnTour.setForeground(new java.awt.Color(0, 0, 0));
        btnTour.setText("TOUR");
        btnTour.setBorder(null);
        jPanel3.add(btnTour);
        btnTour.setBounds(0, 0, 150, 38);

        btnKHTour.setBackground(new java.awt.Color(153, 153, 255));
        btnKHTour.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnKHTour.setForeground(new java.awt.Color(0, 0, 0));
        btnKHTour.setText("KẾ HOẠCH TOUR");
        btnKHTour.setBorder(null);
        jPanel3.add(btnKHTour);
        btnKHTour.setBounds(0, 40, 150, 38);

        btnDiaDiem.setBackground(new java.awt.Color(153, 153, 255));
        btnDiaDiem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDiaDiem.setForeground(new java.awt.Color(0, 0, 0));
        btnDiaDiem.setText("ĐỊA ĐIỂM");
        btnDiaDiem.setBorder(null);
        jPanel3.add(btnDiaDiem);
        btnDiaDiem.setBounds(0, 80, 150, 38);

        btnHopDong.setBackground(new java.awt.Color(153, 153, 255));
        btnHopDong.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnHopDong.setForeground(new java.awt.Color(0, 0, 0));
        btnHopDong.setText("HỢP ĐỒNG");
        btnHopDong.setBorder(null);
        jPanel3.add(btnHopDong);
        btnHopDong.setBounds(0, 120, 150, 38);

        btnKhachHang.setBackground(new java.awt.Color(153, 153, 255));
        btnKhachHang.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnKhachHang.setForeground(new java.awt.Color(0, 0, 0));
        btnKhachHang.setText("KHÁCH HÀNG");
        btnKhachHang.setBorder(null);
        jPanel3.add(btnKhachHang);
        btnKhachHang.setBounds(0, 160, 150, 38);

        btnNhanVien.setBackground(new java.awt.Color(153, 153, 255));
        btnNhanVien.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnNhanVien.setForeground(new java.awt.Color(0, 0, 0));
        btnNhanVien.setText("NHÂN VIÊN");
        btnNhanVien.setBorder(null);
        jPanel3.add(btnNhanVien);
        btnNhanVien.setBounds(0, 200, 150, 38);

        btnThuChi.setBackground(new java.awt.Color(153, 153, 255));
        btnThuChi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnThuChi.setForeground(new java.awt.Color(0, 0, 0));
        btnThuChi.setText("THU CHI");
        btnThuChi.setBorder(null);
        jPanel3.add(btnThuChi);
        btnThuChi.setBounds(0, 240, 150, 38);

        jPanel5.add(jPanel3);
        jPanel3.setBounds(0, 109, 150, 320);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDesktopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesktopActionPerformed
        // TODO add your handling code here:
        GiaoDienDesktop desktop = new GiaoDienDesktop();
        desktop.setVisible(true);
    }//GEN-LAST:event_btnDesktopActionPerformed

    private void btnPhuongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhuongTienActionPerformed
        // TODO add your handling code here:
        PhuongTienGUI ptGUI = new PhuongTienGUI();
        ptGUI.setVisible(true);
    }//GEN-LAST:event_btnPhuongTienActionPerformed

    private void btnNhaHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhaHangActionPerformed
        // TODO add your handling code here:
        NhaHangGUI nhGUI = new NhaHangGUI();
        nhGUI.setVisible(true);
    }//GEN-LAST:event_btnNhaHangActionPerformed

    private void btnKhachSanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachSanActionPerformed
        // TODO add your handling code here:
        KhachSanGUI ksGUI = new KhachSanGUI();
        ksGUI.setVisible(true);
    }//GEN-LAST:event_btnKhachSanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienUngDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienUngDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienUngDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienUngDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienUngDung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesktop;
    private javax.swing.JButton btnDiaDiem;
    private javax.swing.JButton btnHopDong;
    private javax.swing.JButton btnKHTour;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnKhachSan;
    private javax.swing.JButton btnNhaHang;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnPhuongTien;
    private javax.swing.JButton btnThuChi;
    private javax.swing.JButton btnTour;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
